const asirTips = [
    { subject: "Administración de sistemas", ra: "RA1", text: "En Linux, el comando 'grep -r' busca una cadena de texto de forma recursiva en todos los archivos de un directorio." },
    { subject: "Seguridad y alta disponibilidad", ra: "RA1", text: "El principio de mínimo privilegio dicta que los usuarios deben tener solo los accesos necesarios para realizar su trabajo." },
    { subject: "Servicios de red e Internet", ra: "RA1", text: "El registro MX en una zona DNS especifica el servidor encargado de recibir los correos electrónicos para ese dominio." },
    { subject: "Bases de datos", ra: "RA1", text: "Una clave primaria (Primary Key) debe ser única y no puede contener valores nulos (NULL)." },
    { subject: "Implantación de aplicaciones web", ra: "RA1", text: "HTTPS utiliza TLS/SSL para cifrar la comunicación entre el navegador y el servidor, protegiendo los datos." },
    { subject: "Inglés profesional", ra: "RA1", text: "El 'Past Perfect' (had + participio) se utiliza para describir una acción que ocurrió antes de otro momento en el pasado." },
    { subject: "Seguridad y alta disponibilidad", ra: "RA2", text: "Un ataque de denegación de servicio (DoS) busca saturar los recursos de un sistema para que no pueda atender peticiones legítimas." },
    { subject: "Bases de datos", ra: "RA2", text: "La integridad referencial asegura que las relaciones entre tablas se mantengan consistentes mediante claves foráneas." },
    { subject: "Administración de sistemas", ra: "RA2", text: "En Windows Server, el comando 'gpupdate /force' aplica de forma inmediata los cambios realizados en las directivas de grupo." },
    { subject: "Servicios de red e Internet", ra: "RA2", text: "El protocolo DHCP utiliza cuatro pasos principales: Discovery, Offer, Request y Acknowledgment (DORA)." },
    { subject: "Implantación de aplicaciones web", ra: "RA2", text: "El archivo 'package.json' en proyectos Node.js gestiona las dependencias, scripts y metadatos del proyecto." },
    { subject: "Inglés profesional", ra: "RA2", text: "La expresión 'looking forward to' siempre va seguida de un verbo terminado en '-ing' (ej: looking forward to meeting you)." },
    { subject: "Administración de sistemas", ra: "RA3", text: "El comando 'top' o 'htop' en Linux muestra en tiempo real los procesos que más recursos consumen del sistema." },
    { subject: "Seguridad y alta disponibilidad", ra: "RA3", text: "El cifrado simétrico (como AES) es más rápido que el asimétrico y se usa para cifrar grandes volúmenes de datos." },
    { subject: "Bases de datos", ra: "RA3", text: "La sentencia 'GROUP BY' en SQL se utiliza para agrupar filas que tienen los mismos valores en columnas especificadas." },
    { subject: "Servicios de red e Internet", ra: "RA3", text: "Un servidor proxy actúa como intermediario entre un cliente y el servidor final, pudiendo filtrar o cachear contenido." },
    { subject: "Implantación de aplicaciones web", ra: "RA3", text: "El framework Bootstrap permite crear diseños web 'responsive' rápidamente mediante su sistema de rejilla (grid)." },
    { subject: "Inglés profesional", ra: "RA3", text: "Los 'Conditionals' expresan situaciones hipotéticas. El 'Second Conditional' usa Past Simple + Would para hipótesis presentes." },
    { subject: "Seguridad y alta disponibilidad", ra: "RA4", text: "El sistema RAID 10 combina el rendimiento de RAID 0 (stripping) con la seguridad de RAID 1 (mirroring)." },
    { subject: "Administración de sistemas", ra: "RA4", text: "En PowerShell, los 'cmdlets' siguen la estructura Verbo-Sustantivo (ej: Get-Service, Start-Process)." },
    { subject: "Bases de datos", ra: "RA4", text: "Los disparadores (triggers) son bloques de código que se ejecutan automáticamente ante eventos INSERT, UPDATE o DELETE." },
    { subject: "Servicios de red e Internet", ra: "RA4", text: "El protocolo SNMP permite a los administradores de red gestionar y supervisar el funcionamiento de los dispositivos de red." },
    { subject: "Implantación de aplicaciones web", ra: "RA4", text: "Docker permite empaquetar una aplicación con todas sus dependencias en un contenedor para asegurar que funcione en cualquier entorno." },
    { subject: "Inglés profesional", ra: "RA4", text: "En un entorno profesional, es preferible usar 'Could you...?' o 'Would you mind...?' para hacer peticiones de forma educada." },
    { subject: "Administración de sistemas", ra: "RA5", text: "El comando 'df -h' en Linux muestra el espacio libre y ocupado en los diferentes sistemas de archivos montados." },
    { subject: "Seguridad y alta disponibilidad", ra: "RA5", text: "Un backup incremental solo copia los datos que han cambiado desde la última copia de seguridad (ya sea total o incremental)." },
    { subject: "Bases de datos", ra: "RA5", text: "Un procedimiento almacenado (Stored Procedure) es una consulta SQL precompilada que se guarda en el servidor para ser reutilizada." },
    { subject: "Servicios de red e Internet", ra: "RA5", text: "El protocolo IMAP permite acceder a los correos electrónicos directamente en el servidor sin necesidad de descargarlos localmente." },
    { subject: "Implantación de aplicaciones web", ra: "RA5", text: "El almacenamiento local (localStorage) permite guardar datos en el navegador del usuario de forma persistente." },
    { subject: "Inglés profesional", ra: "RA5", text: "Las 'Passive Voice' (be + participio) son muy comunes en informes técnicos para centrar la atención en la acción y no en el sujeto." },
    { subject: "Administración de sistemas", ra: "RA6", text: "El comando 'sudo' permite a usuarios autorizados ejecutar comandos con los privilegios del superusuario (root)." },
    { subject: "Seguridad y alta disponibilidad", ra: "RA6", text: "Un IDS (Intrusion Detection System) monitoriza el tráfico de red en busca de patrones sospechosos o ataques conocidos." },
    { subject: "Servicios de red e Internet", ra: "RA6", text: "El comando 'traceroute' (Linux) o 'tracert' (Windows) muestra la ruta que siguen los paquetes hasta un destino." },
    { subject: "Implantación de aplicaciones web", ra: "RA6", text: "El motor de plantillas en el lado del servidor (como EJS o Handlebars) genera HTML dinámico inyectando datos." },
    { subject: "Bases de datos", ra: "RA1", text: "El lenguaje SQL se divide en DDL (definición de datos), DML (manipulación) y DCL (control)." },
    { subject: "Seguridad y alta disponibilidad", ra: "RA3", text: "La firma digital garantiza la autenticidad, la integridad y el no repudio de un mensaje o documento." },
    { subject: "Inglés profesional", ra: "RA6", text: "Vocabulario clave: 'Uptime' (tiempo de actividad), 'Downtime' (tiempo de inactividad), 'Scalability' (escalabilidad)." },
];
